/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Package;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Add extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form Add
     */
    public Add() {
        super("AddBook");
        initComponents();
        conn = DBconnection.getConnection();
        setLocationRelativeTo(null);
        
    }
static ImageIcon ii;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogBook = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        booktitle = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        edition = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        rowno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        bookshelf = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        add = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDialogStudent = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        studentid = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        regno = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        firstname = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        lastname = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        grade = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        contactno = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        add1 = new javax.swing.JLabel();
        clear1 = new javax.swing.JLabel();
        close2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        Traveller = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Btn6 = new javax.swing.JLabel();
        Btn3 = new javax.swing.JLabel();
        Btn5 = new javax.swing.JLabel();
        Btn1 = new javax.swing.JLabel();
        Btn2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        U1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        U2 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();

        jDialogBook.setTitle("Add Book");
        jDialogBook.setMaximumSize(new java.awt.Dimension(460, 610));
        jDialogBook.setMinimumSize(new java.awt.Dimension(460, 610));
        jDialogBook.setUndecorated(true);
        jDialogBook.setSize(new java.awt.Dimension(460, 610));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Book ID :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 31));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ISBN :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 31));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Book Title :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 80, 31));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Author :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 31));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Edition :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 31));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Book Type :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 80, 31));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Price :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 80, 31));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Publisher :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 80, 31));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Book Shelf :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 80, 31));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Row No :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 80, 31));

        bookid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookid.setForeground(new java.awt.Color(102, 102, 102));
        bookid.setBorder(null);
        bookid.setOpaque(false);
        bookid.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel5.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 250, 31));

        isbn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        isbn.setForeground(new java.awt.Color(102, 102, 102));
        isbn.setBorder(null);
        isbn.setOpaque(false);
        isbn.setSelectionColor(new java.awt.Color(0, 153, 0));
        isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                isbnFocusGained(evt);
            }
        });
        jPanel5.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 250, 31));

        booktitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        booktitle.setForeground(new java.awt.Color(102, 102, 102));
        booktitle.setBorder(null);
        booktitle.setOpaque(false);
        booktitle.setSelectionColor(new java.awt.Color(0, 153, 0));
        booktitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                booktitleFocusGained(evt);
            }
        });
        jPanel5.add(booktitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, 31));

        author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        author.setForeground(new java.awt.Color(102, 102, 102));
        author.setBorder(null);
        author.setOpaque(false);
        author.setSelectionColor(new java.awt.Color(0, 153, 0));
        author.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                authorFocusGained(evt);
            }
        });
        jPanel5.add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, 31));

        edition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edition.setForeground(new java.awt.Color(102, 102, 102));
        edition.setBorder(null);
        edition.setOpaque(false);
        edition.setSelectionColor(new java.awt.Color(0, 153, 0));
        edition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editionFocusGained(evt);
            }
        });
        jPanel5.add(edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 250, 31));

        type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        type.setForeground(new java.awt.Color(102, 102, 102));
        type.setBorder(null);
        type.setOpaque(false);
        type.setSelectionColor(new java.awt.Color(0, 153, 0));
        type.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typeFocusGained(evt);
            }
        });
        jPanel5.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 250, 31));

        price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        price.setForeground(new java.awt.Color(102, 102, 102));
        price.setBorder(null);
        price.setOpaque(false);
        price.setSelectionColor(new java.awt.Color(0, 153, 0));
        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
        });
        jPanel5.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 250, 31));

        publisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        publisher.setForeground(new java.awt.Color(102, 102, 102));
        publisher.setBorder(null);
        publisher.setOpaque(false);
        publisher.setSelectionColor(new java.awt.Color(0, 153, 0));
        publisher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                publisherFocusGained(evt);
            }
        });
        jPanel5.add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 250, 31));

        rowno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rowno.setForeground(new java.awt.Color(102, 102, 102));
        rowno.setBorder(null);
        rowno.setOpaque(false);
        rowno.setSelectionColor(new java.awt.Color(0, 153, 0));
        rowno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rownoFocusGained(evt);
            }
        });
        jPanel5.add(rowno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 250, 31));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 260, 10));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 260, 10));

        bookshelf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookshelf.setForeground(new java.awt.Color(102, 102, 102));
        bookshelf.setBorder(null);
        bookshelf.setOpaque(false);
        bookshelf.setSelectionColor(new java.awt.Color(0, 153, 0));
        bookshelf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bookshelfFocusGained(evt);
            }
        });
        jPanel5.add(bookshelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 250, 31));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 260, 10));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 260, 10));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 260, 10));

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, 10));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 10));

        add.setBackground(new java.awt.Color(60, 0, 60));
        add.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("   ADD");
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jPanel5.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 230, 50));

        clear.setBackground(new java.awt.Color(102, 0, 102));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("  CLEAR");
        clear.setOpaque(true);
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        jPanel5.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 230, 50));

        close1.setBackground(new java.awt.Color(255, 255, 255));
        close1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(102, 102, 102));
        close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close1.setText("X");
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close1MouseExited(evt);
            }
        });
        jPanel5.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 0, 50, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Add_18px.png"))); // NOI18N
        jLabel7.setText(" Add Book");
        jLabel7.setOpaque(true);
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 456, 30));

        javax.swing.GroupLayout jDialogBookLayout = new javax.swing.GroupLayout(jDialogBook.getContentPane());
        jDialogBook.getContentPane().setLayout(jDialogBookLayout);
        jDialogBookLayout.setHorizontalGroup(
            jDialogBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogBookLayout.setVerticalGroup(
            jDialogBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogStudent.setTitle("Add Student");
        jDialogStudent.setMaximumSize(new java.awt.Dimension(431, 560));
        jDialogStudent.setMinimumSize(new java.awt.Dimension(431, 560));
        jDialogStudent.setUndecorated(true);
        jDialogStudent.setPreferredSize(new java.awt.Dimension(431, 560));
        jDialogStudent.setSize(new java.awt.Dimension(431, 560));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(153, 153, 153)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentid.setForeground(new java.awt.Color(102, 102, 102));
        studentid.setBorder(null);
        studentid.setOpaque(false);
        studentid.setSelectionColor(new java.awt.Color(0, 153, 0));
        studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentidFocusGained(evt);
            }
        });
        jPanel6.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, 31));

        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, 10));

        regno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regno.setForeground(new java.awt.Color(102, 102, 102));
        regno.setBorder(null);
        regno.setOpaque(false);
        regno.setSelectionColor(new java.awt.Color(0, 153, 0));
        regno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regnoFocusGained(evt);
            }
        });
        jPanel6.add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, 31));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, 10));

        firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(102, 102, 102));
        firstname.setBorder(null);
        firstname.setOpaque(false);
        firstname.setSelectionColor(new java.awt.Color(0, 153, 0));
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
        });
        jPanel6.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 230, 31));

        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, 10));

        lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(102, 102, 102));
        lastname.setBorder(null);
        lastname.setOpaque(false);
        lastname.setSelectionColor(new java.awt.Color(0, 153, 0));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
        });
        jPanel6.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 230, 31));

        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 230, 10));

        grade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grade.setForeground(new java.awt.Color(102, 102, 102));
        grade.setBorder(null);
        grade.setOpaque(false);
        grade.setSelectionColor(new java.awt.Color(0, 153, 0));
        grade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gradeFocusGained(evt);
            }
        });
        jPanel6.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 230, 31));

        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 230, 10));

        contactno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contactno.setForeground(new java.awt.Color(102, 102, 102));
        contactno.setBorder(null);
        contactno.setOpaque(false);
        contactno.setSelectionColor(new java.awt.Color(0, 153, 0));
        contactno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactnoFocusGained(evt);
            }
        });
        jPanel6.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 230, 31));

        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 230, 10));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setBorder(null);
        email.setOpaque(false);
        email.setSelectionColor(new java.awt.Color(0, 153, 0));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        jPanel6.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 230, 31));

        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 230, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Reg No :");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 31));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("E-mail :");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 80, 31));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Student ID :");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 31));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("First Name :");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 31));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Last Name :");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 31));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Grade :");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, 31));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Contact No :");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, 31));

        add1.setBackground(new java.awt.Color(60, 0, 60));
        add1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add1.setForeground(new java.awt.Color(255, 255, 255));
        add1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add1.setText("   ADD");
        add1.setMaximumSize(new java.awt.Dimension(210, 50));
        add1.setMinimumSize(new java.awt.Dimension(210, 50));
        add1.setOpaque(true);
        add1.setPreferredSize(new java.awt.Dimension(210, 50));
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
        });
        jPanel6.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 220, 50));

        clear1.setBackground(new java.awt.Color(102, 0, 102));
        clear1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clear1.setForeground(new java.awt.Color(255, 255, 255));
        clear1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear1.setText("  CLEAR");
        clear1.setMaximumSize(new java.awt.Dimension(210, 50));
        clear1.setMinimumSize(new java.awt.Dimension(210, 50));
        clear1.setOpaque(true);
        clear1.setPreferredSize(new java.awt.Dimension(210, 50));
        clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear1MouseClicked(evt);
            }
        });
        jPanel6.add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 210, 50));

        close2.setBackground(new java.awt.Color(255, 255, 255));
        close2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        close2.setForeground(new java.awt.Color(102, 102, 102));
        close2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close2.setText("X");
        close2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close2MouseExited(evt);
            }
        });
        jPanel6.add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 50, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Add_18px.png"))); // NOI18N
        jLabel6.setText(" Add Student");
        jLabel6.setOpaque(true);
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 428, 30));

        javax.swing.GroupLayout jDialogStudentLayout = new javax.swing.GroupLayout(jDialogStudent.getContentPane());
        jDialogStudent.getContentPane().setLayout(jDialogStudentLayout);
        jDialogStudentLayout.setHorizontalGroup(
            jDialogStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogStudentLayout.setVerticalGroup(
            jDialogStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 630));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(244, 244, 244));
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Menu_20px.png"))); // NOI18N
        menu.setOpaque(true);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
                menuagainclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 30));

        Traveller.setBackground(new java.awt.Color(255, 255, 255));
        Traveller.setMaximumSize(new java.awt.Dimension(920, 30));
        Traveller.setOpaque(false);
        Traveller.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TravellerMouseDragged(evt);
            }
        });
        Traveller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TravellerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TravellerMouseReleased(evt);
            }
        });
        Traveller.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(102, 102, 102));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Traveller.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 50, 30));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(204, 0, 204));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Left_20px.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        Traveller.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        Btn6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn6.setForeground(new java.awt.Color(102, 102, 102));
        Btn6.setText("Reports");
        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn6MouseExited(evt);
            }
        });
        Traveller.add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 110, 30));

        Btn3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn3.setForeground(new java.awt.Color(102, 102, 102));
        Btn3.setText("Remove");
        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn3MouseClicked(evt);
                Btn3reClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn3MouseExited(evt);
            }
        });
        Traveller.add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 110, 30));

        Btn5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn5.setForeground(new java.awt.Color(102, 102, 102));
        Btn5.setText("Update");
        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn5MouseExited(evt);
            }
        });
        Traveller.add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 110, 30));

        Btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn1.setForeground(new java.awt.Color(102, 102, 102));
        Btn1.setText("Circulation");
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
                Btn1reClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn1MouseExited(evt);
            }
        });
        Traveller.add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 110, 30));

        Btn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn2.setForeground(new java.awt.Color(102, 102, 102));
        Btn2.setText("Registration");
        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2MouseClicked(evt);
                Btn2reClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn2MouseExited(evt);
            }
        });
        Traveller.add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 110, 30));

        jPanel1.add(Traveller, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration /");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add new book or student");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/pnl123.jpg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 220));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 960, 220));

        U1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Add_48px.png"))); // NOI18N
        U1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                U1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                U1MouseExited(evt);
            }
        });
        jPanel1.add(U1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 100, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Book");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Student");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 100, -1));

        U2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        U2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Add_User_Male_48px.png"))); // NOI18N
        U2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                U2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                U2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                U2MouseExited(evt);
            }
        });
        jPanel1.add(U2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 100, 100));

        m1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Circled_Thin_20px.png"))); // NOI18N
        jPanel1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        m2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Circled_Thin_20px.png"))); // NOI18N
        jPanel1.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setBackground(new java.awt.Color(51, 51, 51));
        A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Home_20px.png"))); // NOI18N
        A1.setOpaque(true);
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        jPanel2.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        A2.setBackground(new java.awt.Color(0, 0, 0));
        A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Search_20px.png"))); // NOI18N
        A2.setOpaque(true);
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        jPanel2.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 40));

        A3.setBackground(new java.awt.Color(0, 0, 0));
        A3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_About_20px.png"))); // NOI18N
        A3.setOpaque(true);
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });
        jPanel2.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 40));

        A4.setBackground(new java.awt.Color(0, 0, 0));
        A4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A4.setOpaque(true);
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });
        jPanel2.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 70, 600));

        L5.setBackground(new java.awt.Color(0, 0, 0));
        L5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L5.setForeground(new java.awt.Color(204, 204, 204));
        L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L5.setOpaque(true);
        jPanel1.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 190, 110, 440));

        L4.setBackground(new java.awt.Color(0, 0, 0));
        L4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L4.setForeground(new java.awt.Color(204, 204, 204));
        L4.setOpaque(true);
        jPanel1.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 150, 110, 40));

        L3.setBackground(new java.awt.Color(0, 0, 0));
        L3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L3.setForeground(new java.awt.Color(204, 204, 204));
        L3.setText("   About");
        L3.setOpaque(true);
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 110, 110, 40));

        L2.setBackground(new java.awt.Color(0, 0, 0));
        L2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L2.setForeground(new java.awt.Color(204, 204, 204));
        L2.setText("   Search");
        L2.setOpaque(true);
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 70, 110, 40));

        L1.setBackground(new java.awt.Color(51, 51, 51));
        L1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setText("   Home");
        L1.setOpaque(true);
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 30, 110, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xy,xx;
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
         System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_closeMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        Home L = new Home();
        L.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_backMouseExited

    private void TravellerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_TravellerMouseDragged

    private void TravellerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMousePressed
        setOpacity((float) 0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_TravellerMousePressed

    private void TravellerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_TravellerMouseReleased

    private void U1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U1MouseEntered
        ii = new ImageIcon(getClass().getResource("icons8_Add_48px_1.png"));
        U1.setIcon(ii);
    }//GEN-LAST:event_U1MouseEntered

    private void U1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U1MouseExited
        ii = new ImageIcon(getClass().getResource("icons8_Add_48px.png"));
        U1.setIcon(ii);
    }//GEN-LAST:event_U1MouseExited

    private void U1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U1MouseClicked
        ii = new ImageIcon(getClass().getResource("icons8_New_Moon_20px.png"));
        m1.setIcon(ii);
        ii = new ImageIcon(getClass().getResource("icons8_Circled_Thin_20px.png"));
        m2.setIcon(ii);
       
        jDialogBook.setVisible(true);
        jDialogBook.setLocationRelativeTo(null);
    }//GEN-LAST:event_U1MouseClicked

    private void U2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U2MouseClicked
        ii = new ImageIcon(getClass().getResource("icons8_New_Moon_20px.png"));
        m2.setIcon(ii); 
        ii = new ImageIcon(getClass().getResource("icons8_Circled_Thin_20px.png"));
        m1.setIcon(ii);
        
        jDialogStudent.setVisible(true);
        jDialogStudent.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_U2MouseClicked

    private void U2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U2MouseEntered
         ii = new ImageIcon(getClass().getResource("icons8_Add_User_Male_48px_1.png"));
        U2.setIcon(ii);
    }//GEN-LAST:event_U2MouseEntered

    private void U2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_U2MouseExited
        ii = new ImageIcon(getClass().getResource("icons8_Add_User_Male_48px.png"));
        U2.setIcon(ii);
    }//GEN-LAST:event_U2MouseExited

    private void isbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_isbnFocusGained
        //isbn.setText("");
    }//GEN-LAST:event_isbnFocusGained

    private void booktitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_booktitleFocusGained
        //booktitle.setText(" ");
    }//GEN-LAST:event_booktitleFocusGained

    private void authorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorFocusGained
        //author.setText("");
    }//GEN-LAST:event_authorFocusGained

    private void editionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editionFocusGained
        //edition.setText("");
    }//GEN-LAST:event_editionFocusGained

    private void typeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typeFocusGained
        //type.setText("");
    }//GEN-LAST:event_typeFocusGained

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
        //price.setText("");
    }//GEN-LAST:event_priceFocusGained

    private void publisherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_publisherFocusGained
        //publisher.setText("");
    }//GEN-LAST:event_publisherFocusGained

    private void rownoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rownoFocusGained
        //rowno.setText("");
    }//GEN-LAST:event_rownoFocusGained

    private void bookshelfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookshelfFocusGained
        //bookshelf.setText("");
    }//GEN-LAST:event_bookshelfFocusGained

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        String sql="Insert into books(bookid,isbn,booktitle,author,edition,type,price,publisher,bookshelf,rowno)values(?,?,?,?,?,?,?,?,?,?)";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1,bookid.getText());
            pst.setString(2,isbn.getText());
            pst.setString(3,booktitle.getText());
            pst.setString(4,author.getText());
            pst.setString(5,edition.getText());
            pst.setString(6,type.getText());
            pst.setString(7,price.getText());
            pst.setString(8,publisher.getText());
            pst.setString(9,bookshelf.getText());
            pst.setString(10,rowno.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"New Book Added");
            rs.close();
            pst.close();

        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_addMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked

        bookid.setText(" ");
        isbn.setText(" ");
        booktitle.setText("");
        author.setText(" ");
        edition.setText(" ");
        type.setText(" ");
        price.setText(" ");
        publisher.setText(" ");
        bookshelf.setText(" ");
        rowno.setText(" ");
    }//GEN-LAST:event_clearMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
       add.setBackground(new Color(60,0,60));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(102,0,102));
    }//GEN-LAST:event_addMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
         clear.setBackground(new Color(60,0,60));
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
         clear.setBackground(new Color(102,0,102));
    }//GEN-LAST:event_clearMouseExited

    private void studentidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentidFocusGained
        //studentid.setText("");
    }//GEN-LAST:event_studentidFocusGained

    private void regnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regnoFocusGained
        //regno.setText("");
    }//GEN-LAST:event_regnoFocusGained

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        //firstname.setText("");
    }//GEN-LAST:event_firstnameFocusGained

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
       // lastname.setText("");
    }//GEN-LAST:event_lastnameFocusGained

    private void gradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradeFocusGained
        //grade.setText("");
    }//GEN-LAST:event_gradeFocusGained

    private void contactnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactnoFocusGained
        //contactno.setText("");
    }//GEN-LAST:event_contactnoFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        //email.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        String sql="Insert into students(studentid,regno,firstname,lastname,grade,contactno,email)values(?,?,?,?,?,?,?)";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1,studentid.getText());
            pst.setString(2,regno.getText());
            pst.setString(3,firstname.getText());
            pst.setString(4,lastname.getText());
            pst.setString(5,grade.getText());
            pst.setString(6,contactno.getText());
            pst.setString(7,email.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null,"New Student Added");
            rs.close();
            pst.close();

        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_add1MouseClicked

    private void clear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseClicked
        studentid.setText(" ");
        regno.setText(" ");
        firstname.setText(" ");
        lastname.setText(" ");
        grade.setText(" ");
        contactno.setText(" ");
        email.setText(" ");
    }//GEN-LAST:event_clear1MouseClicked

    private void Btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseClicked
        dispose();
        Reports R = new Reports();
        R.setVisible(true);
    }//GEN-LAST:event_Btn6MouseClicked

    private void Btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn6MouseEntered

    private void Btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn6MouseExited

    private void Btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseClicked

        Btn3.setBackground(new Color(240,240,240));
        Btn1.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        dispose();
        remove a = new remove ();
        a.setVisible(true);
    }//GEN-LAST:event_Btn3MouseClicked

    private void Btn3reClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3reClicked

    }//GEN-LAST:event_Btn3reClicked

    private void Btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseEntered
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYDown(-196, 30, 1, 1, H3);
    }//GEN-LAST:event_Btn3MouseEntered

    private void Btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseExited
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYUp(30, -196, 1, 1, H3);
    }//GEN-LAST:event_Btn3MouseExited

    private void Btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseClicked
        Btn3.setBackground(new Color(255,255,255));
        Btn1.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        AnimationClass AC = new AnimationClass();

        dispose();
        Update R = new Update();
        R.setVisible(true);
    }//GEN-LAST:event_Btn5MouseClicked

    private void Btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseEntered
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYDown(-196, 30, 1, 1, H5);
    }//GEN-LAST:event_Btn5MouseEntered

    private void Btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseExited
        // TODO add your handling code here:
        AnimationClass AC = new AnimationClass();
        //  AC.jLabelYUp(30, -196, 1, 1, H5);
    }//GEN-LAST:event_Btn5MouseExited

    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked

        Btn1.setBackground(new Color(240,240,240));
        Btn3.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        dispose();
        Issue a = new Issue ();
        a.setVisible(true);

        //
    }//GEN-LAST:event_Btn1MouseClicked

    private void Btn1reClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1reClicked

    }//GEN-LAST:event_Btn1reClicked

    private void Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseEntered
        AnimationClass AC = new AnimationClass();
        //AC.jLabelYDown(-196, 30, 1, 1, H1);
    }//GEN-LAST:event_Btn1MouseEntered

    private void Btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseExited
        AnimationClass AC = new AnimationClass();
        //AC.jLabelYUp(30, -196, 1, 1, H1);
    }//GEN-LAST:event_Btn1MouseExited

    private void Btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseClicked

        Btn2.setBackground(new Color(240,240,240));
        Btn1.setBackground(new Color(255,255,255));
        Btn3.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        dispose();
        Add a = new Add ();
        a.setVisible(true);
    }//GEN-LAST:event_Btn2MouseClicked

    private void Btn2reClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2reClicked
        AnimationClass AC = new AnimationClass();

    }//GEN-LAST:event_Btn2reClicked

    private void Btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseEntered
        AnimationClass AC = new AnimationClass();
        //AC.jLabelYDown(-196, 30, 1, 1, H2);
    }//GEN-LAST:event_Btn2MouseEntered

    private void Btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseExited
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYUp(30, -196, 1, 1, H2);
    }//GEN-LAST:event_Btn2MouseExited

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        jDialogBook.dispose();
    }//GEN-LAST:event_close1MouseClicked

    private void close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseEntered
        close1.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_close1MouseEntered

    private void close1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseExited
        close1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_close1MouseExited

    private void close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseClicked
        jDialogStudent.dispose();
    }//GEN-LAST:event_close2MouseClicked

    private void close2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseEntered
        close2.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_close2MouseEntered

    private void close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseExited
        close2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_close2MouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        AnimationClass AC = new AnimationClass();

        AC.jLabelXRight(-150, 70, 1, 1, L1);
        AC.jLabelXRight(-150, 70, 1, 1, L2);
        AC.jLabelXRight(-150, 70, 1, 1, L3);
        AC.jLabelXRight(-150, 70, 1, 1, L4);
        AC.jLabelXRight(-150, 70, 1, 1, L5);
    }//GEN-LAST:event_menuMouseClicked

    private void menuagainclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuagainclicked
        AnimationClass AC = new AnimationClass();
        AC.jLabelXLeft(70, -150, 1, 1, L1);
        AC.jLabelXLeft(70, -150, 1, 1, L2);
        AC.jLabelXLeft(70, -150, 1, 1, L3);
        AC.jLabelXLeft(70, -150, 1, 1, L4);
        AC.jLabelXLeft(70, -150, 1, 1, L5);
    }//GEN-LAST:event_menuagainclicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        menu.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        menu.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_menuMouseExited

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        setColor(A1);
        setColor1(L1);
        resetColor(new JLabel[]{A2,A3},new JLabel[]{L2,L3,L5});
        dispose();
        Home S = new Home();
        S.setVisible(true);
    }//GEN-LAST:event_A1MouseClicked

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        setColor(A2);
        setColor1(L2);
        resetColor(new JLabel[]{A1,A3},new JLabel[]{L1,L3,L5});
        dispose();
        Search S = new Search();
        S.setVisible(true);
    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        setColor(A3);
        setColor1(L3);
        resetColor(new JLabel[]{A2,A1},new JLabel[]{L2,L1,L5});
        dispose();
        About S = new About();
        S.setVisible(true);
    }//GEN-LAST:event_A3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked

    }//GEN-LAST:event_A4MouseClicked
 private void setColor(JLabel A){
        A.setBackground(new Color(51,51,51));
    }
     private void setColor1(JLabel L){
        L.setBackground(new Color(51,51,51));
    }
    private void resetColor(JLabel []A,JLabel [] L){
        for(int i=0;i<A.length;i++){
            A[i].setBackground(new Color(0,0,0));
        }
        for(int i=0;i<L.length;i++){
          L[i].setBackground(new Color(0,0,0));
        }
        
    }
     private void setColor2(JLabel Btn){
        Btn.setBackground(new Color(153,0,153));
        Btn.setForeground(new Color(255,255,255));
    }
     
    private void resetColor2(JLabel []Btn){
        for(int i=0;i<Btn.length;i++){
            Btn[i].setBackground(new Color(255,255,255));
            Btn[i].setForeground(new Color(102,102,102));
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel Btn1;
    private javax.swing.JLabel Btn2;
    private javax.swing.JLabel Btn3;
    private javax.swing.JLabel Btn5;
    private javax.swing.JLabel Btn6;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JPanel Traveller;
    private javax.swing.JLabel U1;
    private javax.swing.JLabel U2;
    private javax.swing.JLabel add;
    private javax.swing.JLabel add1;
    private javax.swing.JTextField author;
    private javax.swing.JLabel back;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookshelf;
    private javax.swing.JTextField booktitle;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel clear1;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel close2;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField edition;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField grade;
    private javax.swing.JTextField isbn;
    private javax.swing.JDialog jDialogBook;
    private javax.swing.JDialog jDialogStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField price;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField regno;
    private javax.swing.JTextField rowno;
    private javax.swing.JTextField studentid;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
