/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Package;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class FogotPW extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form FogotPW
     */
    public FogotPW() {
        initComponents();
        conn = DBconnection.getConnection();
        setLocationRelativeTo(null);
        H1.setVisible(false);
        H2.setVisible(false);
        Err1.setVisible(false);
        Err2.setVisible(false);
    }
static ImageIcon ii;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Traveller = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        B2 = new javax.swing.JPanel();
        F1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        F2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        F3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        F4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        Err1 = new javax.swing.JLabel();
        Err2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Line1 = new javax.swing.JLabel();
        refrech = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Line2 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(510, 600));
        setMinimumSize(new java.awt.Dimension(510, 600));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Traveller.setBackground(new java.awt.Color(255, 255, 255));
        Traveller.setOpaque(false);
        Traveller.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TravellerMouseDragged(evt);
            }
        });
        Traveller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TravellerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TravellerMouseReleased(evt);
            }
        });
        Traveller.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(204, 0, 204));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Left_20px.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        Traveller.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(102, 102, 102));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Traveller.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 30));

        jPanel1.add(Traveller, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        B2.setBackground(new java.awt.Color(255, 255, 255));

        F1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        F1.setForeground(new java.awt.Color(153, 153, 153));
        F1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F1.setText("User Name");
        F1.setBorder(null);
        F1.setCaretColor(new java.awt.Color(0, 153, 0));
        F1.setOpaque(false);
        F1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                F1FocusGained(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        F2.setEditable(false);
        F2.setBackground(new java.awt.Color(255, 255, 255));
        F2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        F2.setForeground(new java.awt.Color(153, 153, 153));
        F2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F2.setText(" Name");
        F2.setBorder(null);
        F2.setCaretColor(new java.awt.Color(0, 153, 0));
        F2.setOpaque(false);

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));

        F3.setEditable(false);
        F3.setBackground(new java.awt.Color(255, 255, 255));
        F3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        F3.setForeground(new java.awt.Color(153, 153, 153));
        F3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F3.setText("Security Question");
        F3.setBorder(null);
        F3.setCaretColor(new java.awt.Color(0, 153, 0));
        F3.setOpaque(false);

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));

        F4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        F4.setForeground(new java.awt.Color(153, 153, 153));
        F4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        F4.setText("Answer");
        F4.setBorder(null);
        F4.setCaretColor(new java.awt.Color(0, 153, 0));
        F4.setOpaque(false);
        F4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                F4FocusGained(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));

        Password.setEditable(false);
        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setText("Your password");
        Password.setBorder(null);
        Password.setCaretColor(new java.awt.Color(0, 153, 0));
        Password.setOpaque(false);

        Err1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Err1.setForeground(new java.awt.Color(255, 0, 0));
        Err1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Err1.setText("  Incorrect User Name!  Please try again..");

        Err2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Err2.setForeground(new java.awt.Color(255, 0, 0));
        Err2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Err2.setText("  Incorrect Answer!  Please try again..");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Enter user name :");

        javax.swing.GroupLayout B2Layout = new javax.swing.GroupLayout(B2);
        B2.setLayout(B2Layout);
        B2Layout.setHorizontalGroup(
            B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(F3)
                    .addComponent(F2)
                    .addGroup(B2Layout.createSequentialGroup()
                        .addGroup(B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(B2Layout.createSequentialGroup()
                                .addComponent(Err1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(B2Layout.createSequentialGroup()
                                .addComponent(F1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(B2Layout.createSequentialGroup()
                                .addGroup(B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5)
                                    .addComponent(Err2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(8, 8, 8))
                    .addComponent(Password)
                    .addComponent(jSeparator1)
                    .addGroup(B2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        B2Layout.setVerticalGroup(
            B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(B2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Err1)
                .addGap(40, 40, 40)
                .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, B2Layout.createSequentialGroup()
                        .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Err2)
                        .addGap(76, 76, 76)))
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addGap(88, 88, 88))
        );

        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 340, 510));

        H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/overicon.png"))); // NOI18N
        jPanel1.add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 70, 70));

        H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/overicon.png"))); // NOI18N
        jPanel1.add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 70, 70));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/Search1.png"))); // NOI18N
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 80, 70));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -6, 40, 110));

        Line1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -50, 30, 190));

        refrech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/Refresh.png"))); // NOI18N
        refrech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refrechMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refrechMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refrechMouseExited(evt);
            }
        });
        jPanel1.add(refrech, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 80, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 50, 120));

        Line2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 30, 80));

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/Password.png"))); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 70, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Forgot Password ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xy,xx;
    private void TravellerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_TravellerMouseDragged

    private void TravellerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMousePressed
        setOpacity((float) 0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_TravellerMousePressed

    private void TravellerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_TravellerMouseReleased

    private void F1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_F1FocusGained
        F1.setText("");
        F1.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_F1FocusGained

    private void F4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_F4FocusGained
        F4.setText("");
        F4.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_F4FocusGained

    private void refrechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refrechMouseClicked
        String a1= F1.getText();
        String a2= F4.getText();
        String sql = "select * from adminacc where answer='"+a2+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if (rs.next()){
                Password.setText(rs.getString(5));
                Password.setForeground(new Color(102,0,102));
                Err2.setVisible(false);
                Err1.setVisible(false);
                ii = new ImageIcon(getClass().getResource("Tich.png"));
                refrech.setIcon(ii);
                ii = new ImageIcon(getClass().getResource("passwordTick.png"));
                password.setIcon(ii);
                Line1.setVisible(true);
                
                rs.close();
                pst.close();
            }
            else{
                ii = new ImageIcon(getClass().getResource("Refresh.png"));
                refrech.setIcon(ii);
                ii = new ImageIcon(getClass().getResource("Password.png"));
                password.setIcon(ii);
                Err2.setVisible(true);
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_refrechMouseClicked

    private void refrechMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refrechMouseEntered
                 H1.setVisible(true);
    }//GEN-LAST:event_refrechMouseEntered

    private void refrechMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refrechMouseExited
                H1.setVisible(false);
    }//GEN-LAST:event_refrechMouseExited

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
                H2.setVisible(false);
    }//GEN-LAST:event_searchMouseExited

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
                 H2.setVisible(true);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        String a1= F1.getText();
        String sql = "select * from adminacc where username='"+a1+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if (rs.next()){
                F2.setText(rs.getString(2));
                F3.setText(rs.getString(3));
                Err1.setVisible(false);
                Err2.setVisible(false);
                ii = new ImageIcon(getClass().getResource("Tich.png"));
                search.setIcon(ii);
              
                rs.close();
                pst.close();
            }
            else{
                ii = new ImageIcon(getClass().getResource("Search1.png"));
                search.setIcon(ii);
                ii = new ImageIcon(getClass().getResource("Refresh.png"));
                refrech.setIcon(ii);
                ii = new ImageIcon(getClass().getResource("Password.png"));
                password.setIcon(ii);
                Err1.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_searchMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_backMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);

    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_closeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FogotPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FogotPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FogotPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FogotPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FogotPW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel B2;
    private javax.swing.JLabel Err1;
    private javax.swing.JLabel Err2;
    private javax.swing.JTextField F1;
    private javax.swing.JTextField F2;
    private javax.swing.JTextField F3;
    private javax.swing.JTextField F4;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel Line1;
    private javax.swing.JLabel Line2;
    private javax.swing.JTextField Password;
    private javax.swing.JPanel Traveller;
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel password;
    private javax.swing.JLabel refrech;
    private javax.swing.JLabel search;
    // End of variables declaration//GEN-END:variables
}
