/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Package;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author PC
 */
public class UserSearch extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form UserSearch
     */
    public UserSearch() {
         super("UserSearch");
        initComponents();
        conn = DBconnection.getConnection();
        setLocationRelativeTo(null);
    }
static ImageIcon ii;

private void setColor(JLabel A){
        A.setBackground(new Color(51,51,51));
    }
     private void setColor1(JLabel L){
        L.setBackground(new Color(51,51,51));
    }
    private void resetColor(JLabel []A,JLabel [] L){
        for(int i=0;i<A.length;i++){
            A[i].setBackground(new Color(0,0,0));
        }
        for(int i=0;i<L.length;i++){
          L[i].setBackground(new Color(0,0,0));
        }
        
    }
     private void setColor2(JLabel Btn){
        Btn.setBackground(new Color(153,0,153));
        Btn.setForeground(new Color(255,255,255));
    }
     
    private void resetColor2(JLabel []Btn){
        for(int i=0;i<Btn.length;i++){
            Btn[i].setBackground(new Color(255,255,255));
            Btn[i].setForeground(new Color(102,102,102));
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        Traveller = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Btn2 = new javax.swing.JLabel();
        Btn1 = new javax.swing.JLabel();
        Btn5 = new javax.swing.JLabel();
        Btn3 = new javax.swing.JLabel();
        Btn6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TB = new javax.swing.JPanel();
        TS = new javax.swing.JPanel();
        TRB = new javax.swing.JPanel();
        TIB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Err1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Brerurn = new javax.swing.JRadioButton();
        issue = new javax.swing.JRadioButton();
        student = new javax.swing.JRadioButton();
        book = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        X5 = new javax.swing.JLabel();
        X4 = new javax.swing.JLabel();
        X3 = new javax.swing.JLabel();
        X2 = new javax.swing.JLabel();
        X1 = new javax.swing.JLabel();
        X6 = new javax.swing.JLabel();
        X7 = new javax.swing.JLabel();
        X8 = new javax.swing.JLabel();
        X9 = new javax.swing.JLabel();
        X10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1030, 630));
        setMinimumSize(new java.awt.Dimension(1030, 630));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1030, 630));
        setSize(new java.awt.Dimension(1030, 630));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(244, 244, 244));
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Menu_20px.png"))); // NOI18N
        menu.setOpaque(true);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
                menuagainclicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setBackground(new java.awt.Color(51, 51, 51));
        A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Home_20px.png"))); // NOI18N
        A1.setOpaque(true);
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        jPanel2.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        A2.setBackground(new java.awt.Color(0, 0, 0));
        A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Search_20px.png"))); // NOI18N
        A2.setOpaque(true);
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        jPanel2.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 70, 40));

        A3.setBackground(new java.awt.Color(0, 0, 0));
        A3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_About_20px.png"))); // NOI18N
        A3.setOpaque(true);
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });
        jPanel2.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 40));

        A4.setBackground(new java.awt.Color(0, 0, 0));
        A4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A4.setOpaque(true);
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });
        jPanel2.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 70, 600));

        L5.setBackground(new java.awt.Color(0, 0, 0));
        L5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L5.setForeground(new java.awt.Color(204, 204, 204));
        L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L5.setOpaque(true);
        jPanel1.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 190, 110, 440));

        L4.setBackground(new java.awt.Color(0, 0, 0));
        L4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L4.setForeground(new java.awt.Color(204, 204, 204));
        L4.setOpaque(true);
        jPanel1.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 150, 110, 40));

        L3.setBackground(new java.awt.Color(0, 0, 0));
        L3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L3.setForeground(new java.awt.Color(204, 204, 204));
        L3.setText("   About");
        L3.setOpaque(true);
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 110, 110, 40));

        L2.setBackground(new java.awt.Color(0, 0, 0));
        L2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L2.setForeground(new java.awt.Color(204, 204, 204));
        L2.setText("   Search");
        L2.setOpaque(true);
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 70, 110, 40));

        L1.setBackground(new java.awt.Color(51, 51, 51));
        L1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setText("   Home");
        L1.setOpaque(true);
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 30, 110, 40));

        Traveller.setBackground(new java.awt.Color(255, 255, 255));
        Traveller.setMaximumSize(new java.awt.Dimension(920, 30));
        Traveller.setOpaque(false);
        Traveller.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TravellerMouseDragged(evt);
            }
        });
        Traveller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TravellerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TravellerMouseReleased(evt);
            }
        });
        Traveller.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(102, 102, 102));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Traveller.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 50, 30));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(204, 0, 204));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Left_20px.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        Traveller.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        Btn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn2.setForeground(new java.awt.Color(102, 102, 102));
        Btn2.setText("Registration");
        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2MouseClicked(evt);
                Btn2reClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn2MouseExited(evt);
            }
        });
        Traveller.add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 110, 30));

        Btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn1.setForeground(new java.awt.Color(102, 102, 102));
        Btn1.setText("Circulation");
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
                Btn1reClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn1MouseExited(evt);
            }
        });
        Traveller.add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 110, 30));

        Btn5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn5.setForeground(new java.awt.Color(102, 102, 102));
        Btn5.setText("Update");
        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn5MouseExited(evt);
            }
        });
        Traveller.add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 110, 30));

        Btn3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn3.setForeground(new java.awt.Color(102, 102, 102));
        Btn3.setText("Remove");
        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn3MouseClicked(evt);
                Btn3reClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn3MouseExited(evt);
            }
        });
        Traveller.add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 110, 30));

        Btn6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Btn6.setForeground(new java.awt.Color(102, 102, 102));
        Btn6.setText("Reports");
        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn6MouseExited(evt);
            }
        });
        Traveller.add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 110, 30));

        jPanel1.add(Traveller, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB.setBackground(new java.awt.Color(255, 255, 255));
        TB.setOpaque(false);
        TB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(TB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 211, -1));

        TS.setBackground(new java.awt.Color(255, 255, 255));
        TS.setOpaque(false);
        TS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(TS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 213, -1));

        TRB.setBackground(new java.awt.Color(255, 255, 255));
        TRB.setOpaque(false);
        TRB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(TRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        TIB.setBackground(new java.awt.Color(255, 255, 255));
        TIB.setOpaque(false);
        TIB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(TIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book, Student, issue or return details");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search /");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/pnl123.jpg"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 277));

        Err1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Err1.setForeground(new java.awt.Color(255, 0, 0));
        Err1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Err1.setText("  Incorrect ID !  Please try again..");
        jPanel4.add(Err1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 255, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 960, -1));

        txt1.setBorder(null);
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 230, 30));

        txt2.setBorder(null);
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 230, 30));

        txt3.setBorder(null);
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 230, 30));

        txt4.setBorder(null);
        jPanel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 230, 30));

        txt5.setBorder(null);
        jPanel1.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 230, 30));

        txt6.setBorder(null);
        jPanel1.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 230, 30));

        txt7.setBorder(null);
        jPanel1.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 230, 30));

        txt8.setBorder(null);
        jPanel1.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 230, 30));

        txt9.setBorder(null);
        jPanel1.add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 230, 30));

        txt10.setBorder(null);
        jPanel1.add(txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 230, 30));

        id.setBackground(new java.awt.Color(240, 240, 240));
        id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("Search");
        id.setBorder(null);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 310, 30));

        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_Package/icons8_Search_20px.png"))); // NOI18N
        search.setOpaque(true);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 40, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        Brerurn.setBackground(new java.awt.Color(255, 255, 255));
        Brerurn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Brerurn.setForeground(new java.awt.Color(102, 102, 102));
        Brerurn.setText("Return");
        Brerurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrerurnActionPerformed(evt);
            }
        });

        issue.setBackground(new java.awt.Color(255, 255, 255));
        issue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issue.setForeground(new java.awt.Color(102, 102, 102));
        issue.setText("Issue");

        student.setBackground(new java.awt.Color(255, 255, 255));
        student.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        student.setForeground(new java.awt.Color(102, 102, 102));
        student.setText("Student");

        book.setBackground(new java.awt.Color(255, 255, 255));
        book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        book.setForeground(new java.awt.Color(102, 102, 102));
        book.setText("book");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(book)
                .addGap(10, 10, 10)
                .addComponent(student)
                .addGap(18, 18, 18)
                .addComponent(issue)
                .addGap(18, 18, 18)
                .addComponent(Brerurn)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book)
                    .addComponent(student)
                    .addComponent(issue)
                    .addComponent(Brerurn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 310, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Select what you Looking for...");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, 30));

        X5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X5.setForeground(new java.awt.Color(102, 102, 102));
        X5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 110, 30));

        X4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X4.setForeground(new java.awt.Color(102, 102, 102));
        X4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 110, 30));

        X3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X3.setForeground(new java.awt.Color(102, 102, 102));
        X3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 110, 30));

        X2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X2.setForeground(new java.awt.Color(102, 102, 102));
        X2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 110, 30));

        X1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X1.setForeground(new java.awt.Color(102, 102, 102));
        X1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 110, 30));

        X6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X6.setForeground(new java.awt.Color(102, 102, 102));
        X6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 110, 30));

        X7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X7.setForeground(new java.awt.Color(102, 102, 102));
        X7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 110, 30));

        X8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X8.setForeground(new java.awt.Color(102, 102, 102));
        X8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 110, 30));

        X9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X9.setForeground(new java.awt.Color(102, 102, 102));
        X9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 110, 30));

        X10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X10.setForeground(new java.awt.Color(102, 102, 102));
        X10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(X10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 110, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int xy,xx;
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       System.exit(0);

    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(60,60,60));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_closeMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        Home L = new Home();
        L.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_backMouseExited

    private void TravellerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_TravellerMouseDragged

    private void TravellerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMousePressed
        setOpacity((float) 0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_TravellerMousePressed

    private void TravellerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravellerMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_TravellerMouseReleased

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        String a1= id.getText();
        if(book.isSelected()){
            String sql = "select * from books where bookid='"+a1+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if (rs.next()){
                    txt1.setText(rs.getString(2));
                    txt2.setText(rs.getString(3));
                    txt3.setText(rs.getString(4));
                    txt4.setText(rs.getString(5));
                    txt5.setText(rs.getString(6));
                    txt6.setText(rs.getString(7));
                    txt7.setText(rs.getString(8));
                    txt8.setText(rs.getString(9));
                    txt9.setText(rs.getString(10));
                    // txt10.setText(rs.getString(10));

                    X1.setText("ISBN : ");
                    X2.setText("Book Title : ");
                    X3.setText("Author : ");
                    X4.setText("Edtion : ");
                    X5.setText("Type : ");
                    X6.setText("Price : ");
                    X7.setText("Publisher : ");
                    X8.setText("Book Shelf : ");
                    X9.setText("Row No : ");

                    Err1.setVisible(false);
                    rs.close();
                    pst.close();
                }
                else{
                    Err1.setVisible(true);
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        else if(student.isSelected()){
            String sql = "select * from students where studentid='"+a1+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if (rs.next()){
                    txt1.setText(rs.getString(2));
                    txt2.setText(rs.getString(3));
                    txt3.setText(rs.getString(4));
                    txt4.setText(rs.getString(5));
                    txt5.setText(rs.getString(6));
                    txt6.setText(rs.getString(7));

                    X1.setText("Reg No : ");
                    X2.setText("First Name : ");
                    X3.setText("Last Name : ");
                    X4.setText("Grade : ");
                    X5.setText("Contact No : ");
                    X6.setText("Email : ");

                    Err1.setVisible(false);
                    rs.close();
                    pst.close();
                }
                else{
                    Err1.setVisible(true);
                }
            }catch(Exception ex){
                //JOptionPane.showMessageDialog(null,ex);
            }
        }
        else if(issue.isSelected()){
            String sql = "select * from issuebook where studentid='"+a1+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if (rs.next()){
                    txt1.setText(rs.getString(2));
                    txt2.setText(rs.getString(3));
                    txt3.setText(rs.getString(4));
                    txt4.setText(rs.getString(5));
                    txt5.setText(rs.getString(6));
                    txt6.setText(rs.getString(7));
                    X1.setText("Reg No : ");
                    X2.setText("First Name : ");
                    X3.setText("Book ID : ");
                    X4.setText("ISBN : ");
                    X5.setText("Book Title : ");
                    X6.setText("Author : ");
                    X7.setText("Issue Date : ");

                    Err1.setVisible(false);
                    rs.close();
                    pst.close();
                }
                else{
                    Err1.setVisible(true);
                }
            }catch(Exception ex){
                //JOptionPane.showMessageDialog(null,ex);
            }
        }
        else if(Brerurn.isSelected()){
            String sql = "select * from returnbook where studentid='"+a1+"'";
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if (rs.next()){
                    txt1.setText(rs.getString(2));
                    txt2.setText(rs.getString(3));
                    txt3.setText(rs.getString(4));
                    txt4.setText(rs.getString(5));
                    txt5.setText(rs.getString(6));
                    txt6.setText(rs.getString(7));
                    txt7.setText(rs.getString(8));

                    X1.setText("Reg No : ");
                    X2.setText("First Name : ");
                    X3.setText("Book ID : ");
                    X4.setText("ISBN : ");
                    X5.setText("Book Title : ");
                    X6.setText("Author : ");
                    X7.setText("Issue Date : ");
                    X8.setText("Return Date : ");

                    Err1.setVisible(false);
                    rs.close();
                    pst.close();
                }
                else{
                    Err1.setVisible(true);
                }
            }catch(Exception ex){
                //JOptionPane.showMessageDialog(null,ex);
            }
        }
    }//GEN-LAST:event_searchMouseClicked

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        search.setOpaque(true);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        search.setOpaque(false);
    }//GEN-LAST:event_searchMouseExited

    private void BrerurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrerurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrerurnActionPerformed

    private void Btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseClicked

        Btn2.setBackground(new Color(240,240,240));
        Btn1.setBackground(new Color(255,255,255));
        Btn3.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        Btn6.setBackground(new Color(255,255,255));
        JOptionPane.showMessageDialog(null,"Sorry ! Only Admin can enter this page");
    }//GEN-LAST:event_Btn2MouseClicked

    private void Btn2reClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2reClicked
        AnimationClass AC = new AnimationClass();
    }//GEN-LAST:event_Btn2reClicked

    private void Btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseEntered
        AnimationClass AC = new AnimationClass();
        //AC.jLabelYDown(-196, 30, 1, 1, H2);
    }//GEN-LAST:event_Btn2MouseEntered

    private void Btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseExited
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYUp(30, -196, 1, 1, H2);
    }//GEN-LAST:event_Btn2MouseExited

    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked

        Btn1.setBackground(new Color(240,240,240));
        Btn3.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        Btn6.setBackground(new Color(255,255,255));
        JOptionPane.showMessageDialog(null,"Sorry ! Only Admin can enter this page");

        //
    }//GEN-LAST:event_Btn1MouseClicked

    private void Btn1reClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1reClicked

    }//GEN-LAST:event_Btn1reClicked

    private void Btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseEntered
        AnimationClass AC = new AnimationClass();
        //AC.jLabelYDown(-196, 30, 1, 1, H1);
    }//GEN-LAST:event_Btn1MouseEntered

    private void Btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseExited
        AnimationClass AC = new AnimationClass();
        //AC.jLabelYUp(30, -196, 1, 1, H1);
    }//GEN-LAST:event_Btn1MouseExited

    private void Btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseClicked
        Btn3.setBackground(new Color(255,255,255));
        Btn1.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        Btn6.setBackground(new Color(255,255,255));
        AnimationClass AC = new AnimationClass();

        JOptionPane.showMessageDialog(null,"Sorry ! Only Admin can enter this page");
    }//GEN-LAST:event_Btn5MouseClicked

    private void Btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseEntered
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYDown(-196, 30, 1, 1, H5);
    }//GEN-LAST:event_Btn5MouseEntered

    private void Btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseExited
        // TODO add your handling code here:
        AnimationClass AC = new AnimationClass();
        //  AC.jLabelYUp(30, -196, 1, 1, H5);
    }//GEN-LAST:event_Btn5MouseExited

    private void Btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseClicked

        Btn3.setBackground(new Color(240,240,240));
        Btn1.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        Btn6.setBackground(new Color(255,255,255));
        JOptionPane.showMessageDialog(null,"Sorry ! Only Admin can enter this page");
    }//GEN-LAST:event_Btn3MouseClicked

    private void Btn3reClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3reClicked

    }//GEN-LAST:event_Btn3reClicked

    private void Btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseEntered
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYDown(-196, 30, 1, 1, H3);
    }//GEN-LAST:event_Btn3MouseEntered

    private void Btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseExited
        AnimationClass AC = new AnimationClass();
        // AC.jLabelYUp(30, -196, 1, 1, H3);
    }//GEN-LAST:event_Btn3MouseExited

    private void Btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseClicked
        Btn6.setBackground(new Color(240,240,240));
        Btn3.setBackground(new Color(255,255,255));
        Btn2.setBackground(new Color(255,255,255));
        Btn5.setBackground(new Color(255,255,255));
        Btn1.setBackground(new Color(255,255,255));
        dispose();
        Reports R = new Reports();
        R.setVisible(true);
    }//GEN-LAST:event_Btn6MouseClicked

    private void Btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn6MouseEntered

    private void Btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn6MouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        AnimationClass AC = new AnimationClass();

        AC.jLabelXRight(-150, 70, 1, 1, L1);
        AC.jLabelXRight(-150, 70, 1, 1, L2);
        AC.jLabelXRight(-150, 70, 1, 1, L3);
        AC.jLabelXRight(-150, 70, 1, 1, L4);
        AC.jLabelXRight(-150, 70, 1, 1, L5);
    }//GEN-LAST:event_menuMouseClicked

    private void menuagainclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuagainclicked
        AnimationClass AC = new AnimationClass();
        AC.jLabelXLeft(70, -150, 1, 1, L1);
        AC.jLabelXLeft(70, -150, 1, 1, L2);
        AC.jLabelXLeft(70, -150, 1, 1, L3);
        AC.jLabelXLeft(70, -150, 1, 1, L4);
        AC.jLabelXLeft(70, -150, 1, 1, L5);
    }//GEN-LAST:event_menuagainclicked

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        menu.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        menu.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_menuMouseExited

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        setColor(A1);
        setColor1(L1);
        resetColor(new JLabel[]{A2,A3},new JLabel[]{L2,L3,L5});
        dispose();
        UserHome S = new UserHome();
        S.setVisible(true);
    }//GEN-LAST:event_A1MouseClicked

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        setColor(A2);
        setColor1(L2);
        resetColor(new JLabel[]{A1,A3},new JLabel[]{L1,L3,L5});
        dispose();
        UserSearch S = new UserSearch();
        S.setVisible(true);
    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        setColor(A3);
        setColor1(L3);
        resetColor(new JLabel[]{A2,A1},new JLabel[]{L2,L1,L5});
        dispose();
        UserAbout S = new UserAbout();
        S.setVisible(true);
    }//GEN-LAST:event_A3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked

    }//GEN-LAST:event_A4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JRadioButton Brerurn;
    private javax.swing.JLabel Btn1;
    private javax.swing.JLabel Btn2;
    private javax.swing.JLabel Btn3;
    private javax.swing.JLabel Btn5;
    private javax.swing.JLabel Btn6;
    private javax.swing.JLabel Err1;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JPanel TB;
    private javax.swing.JPanel TIB;
    private javax.swing.JPanel TRB;
    private javax.swing.JPanel TS;
    private javax.swing.JPanel Traveller;
    private javax.swing.JLabel X1;
    private javax.swing.JLabel X10;
    private javax.swing.JLabel X2;
    private javax.swing.JLabel X3;
    private javax.swing.JLabel X4;
    private javax.swing.JLabel X5;
    private javax.swing.JLabel X6;
    private javax.swing.JLabel X7;
    private javax.swing.JLabel X8;
    private javax.swing.JLabel X9;
    private javax.swing.JLabel back;
    private javax.swing.JRadioButton book;
    private javax.swing.JLabel close;
    private javax.swing.JTextField id;
    private javax.swing.JRadioButton issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel search;
    private javax.swing.JRadioButton student;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
